### ISSUE TITLE
It's ignoring all CSS

### ISSUE THREAD

**Issue by vinimarcili** [cmseguin/rollup-plugin-react-scoped-css#37]
I'm trying to use this plugin with Vite, React + Typescript and Scss files. When I put plugin in vite.config.ts all css is ignored, be it .css, .scss, without or if .scoped.

**Comment by cmseguin** [comment]
Sorry for the delayed response, personal life got really busy.
Can you provide some details on which version of Vite, node & typescript you are using as well as your vite.config.ts you are using?
Thanks

**Comment by vinimarcili** [comment]
Hello!
Unfortunately I don't have vite.config anymore because I ended up going to another solution using create-react-app + craco.js.
But what I can provide is:
Node: 16.14.2
vite: 4.0
Typescript: 4.7.4

But my vite.config was very simple, just with the scoped plugin and another plugin for tspaths
I'm sorry for the lack of information, if that alone doesn't help I'll try to recreate the scenario to send the complete vite.config
