### ISSUE TITLE
Not an issue...

### ISSUE THREAD

**Issue by MarcusSanchez** [cmseguin/rollup-plugin-react-scoped-css#45]
Hey guys, I want to thank you wonderful people for creating this. I've been trying to find a clean way to do styling in react with vite. CSS Modules, although functional, is very limited and just is ugly. I was looking to figure out a way to get styled-jsx to work with vite (btw it doesn't), but I've come across this, which is even better. Now I just have a couple of suggestions/features.
  - When you import the same .scoped.css file in multiple components, just pass the same hash to the other function that imported it as you did on the first. No need to create a new hash and also set up a whole module of css if its the same styles.
  - Also, I don't know the limitations of this, but it would be cool if this was able to work as a single file component, like vue/svelte, like not import the styles from an external file, but in line them. Like styled-jsx, but cleaner? I know with rollup theres alot of compiler magic so I feel its possible. 
  
Either way this is dope and I love you guys.

**Comment by cmseguin** [comment]
Hi :) Thanks for leaving that comment! Sorry if I didn't reply, I didn't really touch my computer this summer! I am glad you enjoy it as much as I do! Not many people like vanilla these days! I get a lot of comment in the like of "but why do I need this plugin if I can use the JSS way" but I think a lot of people just don't know how to write clean CSS/SCSS and miss the point a bit! 

To reply to your first point, I think it's a great idea, I think you are right, it should work that way. I will probably update it at some point when I have more energy to work on this project on my free time!

#2 I was thinking the same, it would definitely be possible but would require quite a bit more work. Right now this plugin is fairly simple and works without many changes to existing projects. But I agree, the way vue does it is quite nice and I was thinking the same at some point. 

If you feel like it, you can always play with it and write a PR for it. I would love to have other people work on this project as well! :)

Anyway, I appreciate the compliments! Thanks!

**Comment by MarcusSanchez** [comment]
No problem, homie. I would love to be able to contribute, however I''m still relatively new to coding (10 months), and understanding preexisting code bases are hard for me, and the plugin api and or rollup aren't familiar to me either. Maybe in the future if I become more competent in this space I would definitely love to give it a shot. But anyways this is very great as it is, I don't know how people like JSS or css modules, this plugin makes things so much easier and cleaner. Thanks anyways.

Also, another thing I've noticed, not that big of an issue just want to bring it to your attention in case you don't know already, if you comment out the import of the *.scoped.css, every html/jsx element still gets the data-v-hash="true" even though there's no style to match.
