### ISSUE TITLE
Vulnerabilities from rollup version

### ISSUE THREAD

**Issue by Oui-Dev** [cmseguin/rollup-plugin-react-scoped-css#61]
It is possible to update the dependencies to use rollup >= 4.22.4 to prevent vulnerabilities ?

**Comment by Thomas-B** [comment]
Adding a comment for visibility :pray: we need our security certifications :pray:

**Comment by cmseguin** [comment]
This should be fixed if you update to 1.1.0

**Comment by Thomas-B** [comment]
@cmseguin thank you :heart:
